[project]
name = "alphamike"
version = "0.9.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Enrico Bartolommei", email = "enricobarto95@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pydantic-settings>=2.15.0",
    "requests>=2.34.2",
]

[project.scripts]
alphamike = "alphamike:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
